"""empty message

Revision ID: 6bd3420e3a30
Revises: 2c7fc1f85682
Create Date: 2021-09-17 17:00:32.771074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bd3420e3a30'
down_revision = '2c7fc1f85682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('test', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
